#!/usr/bin/env bash

# Create binary
cargo build

# Make all need directories
mkdir -p packages/dummyc/DEBIAN
mkdir -p packages/dummyc/usr/bin
mkdir -p packages/dummyc/usr/share/man/man1

# Copy files to locations
cp docs/debian/control packages/dummyc/DEBIAN/control
cp target/debug/dummyc packages/dummyc/usr/bin/dummyc
cp docs/dummyc.1 packages/dummyc/usr/share/man/man1/dummyc.1

# Zip man page file
gzip packages/dummyc/usr/share/man/man1/dummyc.1

# Create .deb
cd packages
dpkg-deb --build dummyc

