#!/usr/bin/env bash

if [ $# != 2 ]
then
  echo "Wrong number of arguments."
  exit
fi

for file in $(ls -1 $1 | grep -v "~"); do
    echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
    echo "Name: $file"
    echo "Output: ~"

    if [ $2 -eq 1 ]
    then
	timeout 5 dummyc $1/$file 2> /dev/null
    fi
    if [ $2 -eq 2 ]
    then
	timeout 5 dummyc $1/$file 1> /dev/null
    fi

    echo "End: ~"
done

echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
