#!/usr/bin/env bash

if [ $# != 3 ]
then
  echo "Wrong number of arguments."
  exit
fi

MODE=$1
PROG_LOC=$2
OUT_LOC=$3

mkdir -p ./test/error_outputs

for file in $(ls -1 $PROG_LOC | grep -v "~"); do
    ./target/debug/dummyc "$PROG_LOC/$file" 2> "./test/error_outputs/${file%.*}_output" 1> /dev/null
done

if [ $1 -eq 0 ]
then
    for file in $(ls -1 ./test/error_outputs | grep -v "~"); do
	cat "./test/error_outputs/$file" | grep "error" > "./test/error_outputs/${file}_post"
	diff --strip-trailing-cr "$OUT_LOC/error_output" "./test/error_outputs/${file}_post" > "./test/diff"
	echo -n "$file: " && [ -s ./test/diff ] && (echo "fail") || (echo "pass")
    done
fi

if [ $1 -eq 2 ]
then
    num_pass=0
    num_fail=0
    num_total=0

    for file in $(ls -1 ./test/error_outputs | grep -v "~"); do
	cat "./test/error_outputs/$file" | grep "error" > "./test/error_outputs/${file}_post"
	diff --strip-trailing-cr "$OUT_LOC/error_output" "./test/error_outputs/${file}_post" > "./test/diff"
	num_total=$(( $num_total + 1 ))

	if [ -s ./test/diff ]
	then
	    num_fail=$(( $num_fail + 1 ))
	else
	    num_pass=$(( $num_pass + 1 ))
	fi
    done

    echo "Total:" $num_total

    if [ $num_total == $num_pass ]
    then
	echo "Status: Testing Passed"
    else
	echo "Status: Testing Failed"
    fi

    echo "=> passed:" $num_pass
    echo "=> failed:" $num_fail
fi

rm -r ./test
