#!/usr/bin/env bash

if [ $# != 1 ]
then
  echo "Wrong number of arguments."
  exit
fi

echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ cargo test ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
cargo test

echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ cargo clippy ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
cargo clippy

echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ cargo build ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
cargo build

echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ custom_test ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
./scripts/program_test $1 ./examples/custom/programs ./examples/custom/outputs

echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ error_test ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
./scripts/error_test $1 ./examples/errors/programs ./examples/errors/outputs

echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ nbs_test ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
./scripts/program_test $1 ./examples/nbs/programs ./examples/nbs/outputs

echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ nbs_error_test ~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
./scripts/error_test $1 ./examples/nbs_errors/programs ./examples/nbs_errors/outputs

echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
