#!/usr/bin/env bash

for file in $(ls -1 ./examples/nbs/programs | grep -v "~"); do
    ./target/debug/dummyc "./examples/nbs/programs/$file" > "/tmp/${file%.*}_output"
done

if [ $1 -eq 0 ]
then
    for file in $(ls -1 ./examples/nbs/outputs | grep -v "~"); do
	diff "./examples/nbs/outputs/$file" "/tmp/$file" > "/tmp/diff"
	echo -n "$file: " && [ -s /tmp/diff ] && (echo "Fail") || (echo "Pass")
    done
fi

if [ $1 -eq 1 ]
then
    for file in $(ls -1 ./examples/nbs/outputs | grep -v "~"); do
	echo "~~~~~~~~~~> $file: "
	cat "/tmp/$file"
    done
fi
