name: Debian

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build
    - name: Make Debian Directory
      run: mkdir -p dummy/DEBIAN
    - name: Make Control File
      run: 'printf "Package: dummy\nVersion: 0.1\nSection: custom\nPriority: optional\nArchitecture: all\nEssential: no\nInstalled-Size: 1024\nMaintainer: tday141@gmail.com\nDescription: Compiler for Minimal Basic (EMCA-55)\n" > ./dummy/DEBIAN/control'
    - name: Make Binary Directory
      run: mkdir -p dummy/usr/bin
    - name: Copy Binary
      run: cp /home/runner/work/dummy_compiler/dummy_compiler/target/debug/dummy_compiler dummy/usr/bin/dummy_compiler
    - name: Build Package
      run: dpkg-deb --build dummy
    - name: Archive Package
      uses: actions/upload-artifact@v2
      with:
        name: debian-package
        path: ./dummy.deb
